### ISSUE TITLE
Update URL upstream

### ISSUE THREAD

**Issue by pombredanne** [nexB/aboutcode-cyclonedx-taxonomy#3]
We need to update the URL @ CycloneDX too. @chinyeungli do you mind to submit a PR upstream too?

**Comment by chinyeungli** [comment]
@pombredanne in here https://github.com/CycloneDX/cyclonedx-property-taxonomy?tab=readme-ov-file ?
asked to update the "Administered By" ?

**Comment by pombredanne** [comment]
Yes, submit a PR with updates to the links in https://github.com/CycloneDX/cyclonedx-property-taxonomy/blob/8be94a54872fc7f14fe3814b83e54d54c10184f3/README.md#L85

**Comment by chinyeungli** [comment]
@pombredanne so should the "Administered By" still be `nexB` or `AboutCode.org` ?

**Comment by pombredanne** [comment]
@chin-yeung AboutCode.org

**Comment by chinyeungli** [comment]
PR submitted: https://github.com/CycloneDX/cyclonedx-property-taxonomy/pull/93
